name: zbd_ramp
description: ZBD Ramp widget for Flutter - Bitcoin Lightning Network payments integration
version: 1.0.0
homepage: https://github.com/zbdpay/ramp-flutter

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: