name: zbd_ramp
description: ZBD Ramp widget for Flutter - Bitcoin Lightning Network payments integration
version: 1.0.0
homepage: https://github.com/zbdpay/ramp-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  permission_handler: ^11.3.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: